// src/components/Source/index.tsx
import { Tabs } from 'antd';
import type { TabsProps } from 'antd';
import VideoSourceTab from './VideoSourceTab';
import ImageSourceTab from './ImageSourceTab';
const Source = () => {
    const items: TabsProps['items'] = [
        {
            key: '1',
            label: '视频',
            children: VideoSourceTab(),
        },
        {
            key: '2',
            label: '图片',
            children: ImageSourceTab(),
        },
        {
            key: '3',
            label: '花字',
            children: 'Content of Tab Pane 3',
        },
        {
            key: '4',
            label: '音频',
            children: 'Content of Tab Pane 3',
        },
    ];
    return (
        <>
            <Tabs defaultActiveKey="1" items={items} centered />
        </>
    )
}
export default Source

// src/components/Source/index.vue
<template>
    <el-tabs v-model="activeTab" stretch>
        <el-tab-pane label="视频" name="1">
            <VideoTab />
        </el-tab-pane>
        <el-tab-pane label="图片" name="2">
            <ImageTab />
        </el-tab-pane>
        <el-tab-pane label="花字" name="3">花字</el-tab-pane>
        <el-tab-pane label="音频" name="4">音频</el-tab-pane>
    </el-tabs>
</template>
<script setup lang="ts">
const activeTab = ref('1')

</script>
